en:
  dashboard:
    welcome_html: |
      %{logo_img_tag}
      <p class="lead">NeSI Training Environment</p>

    shell_app_title: "%{cluster_title} Shell Access (trainers only)"

    pinned_apps_title: 'Training Course Apps'
    pinned_apps_caption_html: ''
