---
- name: Workload | Check for cloud-config secret in {{ cluster_name }}
  shell: >-
    kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig get secrets -A | grep -c cloud-config
  register: cloud_config_secret
  ignore_errors: true

- name: Workload | Install and configure Openstack cloud controller
  block:
    - name: Workload | Create create_cloud_conf.sh
      copy:
        src: "files/create_cloud_conf.sh"
        dest: "{{ tmp_dir }}/create_cloud_conf.sh"
        mode: 0770

    - name: Workload | Prep clouds.yaml for kube secret
      shell: >-
        {{ tmp_dir }}/create_cloud_conf.sh {{ clouds_yaml_location }} {{ clouds_yaml_cloud }} > {{ tmp_dir }}/cloud.conf

    - name: Workload | Generate clouds.yaml secret
      shell: >-
        kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig create secret \
        -n kube-system generic cloud-config --from-file {{ tmp_dir }}/cloud.conf

    - name: Workload | Install cloud-controller-manager-roles.yaml
      shell: >-
        kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig apply \
        -f https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/manifests/controller-manager/cloud-controller-manager-roles.yaml

    - name: Workload | Install cloud-controller-manager-role-bindings.yaml
      shell: >-
        kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig apply \
        -f https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/manifests/controller-manager/cloud-controller-manager-role-bindings.yaml

    - name: Workload | Install openstack-cloud-controller-manager-ds.yaml
      shell: >-
        kubectl --kubeconfig {{ tmp_dir }}/{{ cluster_name }}.kubeconfig apply \
        -f https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  when:
    - cloud_config_secret.stdout != "1"
